# Generated by Django 4.2 on 2023-05-02 15:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Our Team'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_picture),
        ),
    ]
